





---
title: "Data visualization practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message = FALSE}
library(leaflet) # interactive maps
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT) # interactive tables
library(scales)
library(knitr)
```

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```

```{r}
annual_esc <- esc %>% 
  separate(col = sampleDate, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year = as.numeric(year)) %>% 
  group_by(year, SASAP.Region, Species) %>% 
  summarise(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Sockeye", "Chum", "Coho", "Pink", "Chinook"))

annual_esc
```

```{r}
ggplot(annual_esc, mapping = aes(x = Species, y = escapement, fill = SASAP.Region)) + 
  geom_col()
```

```{r}
kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")

ggplot(kodiak_esc, aes(year, escapement, color = Species)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = comma) + # comma comes from scales
  theme_classic() +
  theme(legend.position = "bottom")
```

```{r}
ggplot(annual_esc, aes(x = year, y = escapement,
                       color = Species)) +
    geom_point() +
  geom_line() +
  scale_y_continuous(labels = comma) + # comma comes from scales
  theme_classic() +
  theme(legend.position = "bottom") +
  facet_wrap(~SASAP.Region, scales = "free_y")
```

## Tables

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

datatable(locations) #interactive

kable(locations)

# stargazer package can be used to render statistical output

# gt can also be used to make custom tables. 
```


## Leaflet

```{r}
leaflet(locations) %>% 
  addTiles() %>%  # grabs base tiles for map
  addMarkers(lng = ~Longitude, lat = ~Latitude,
             popup = ~Location)
```

```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```

